services:

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tourbooking
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: specialSystem1234

  db:
    image: postgres:17
    environment:
      - POSTGRES_DB=tourbooking
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=specialSystem1234
    ports:
      - "5437:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tourbooking"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
