spring:
  application:
    name: tour-booking-system-spring

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5437/tourbooking}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:specialSystem1234}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:/db/changelog/master.xml

  messages:
    basename: i18n/messages
    encoding: UTF-8
    fallback-to-system-locale: false

  freemarker:
    expose-spring-macro-helpers: true


server:
  port: 8080